Table "dbo"." DocumentoIdentidd" {
  "idDocumentoIdentidad" int [pk, not null]
  "descripcion" varchar(255) [not null]
  "estado" bit [not null]
  "id_Asociado" int [not null]
}

Table "dbo"."Dueno" {
  "idDueno" int [pk, not null]
  "id_DocumentoIdentidad" int [not null, ref: > "dbo"." DocumentoIdentidd"."idDocumentoIdentidad"]
  "id_Asociado" int [not null, ref: > "dbo"."Asociado"."idAsociado"]
  "nombre" varchar(100) [not null]
  "apellidoPaterno" varchar(100) [not null]
  "apellidoMaterno" varchar(100) [not null]
  "nroDocumento" varchar(20) [not null]
  "nroTelefono" varchar(20)
  "correoElectronico" nvarchar(100)
  "fechaCreacion" datetime [not null]
  "fechaModificacion" datetime
  "fechaEliminacion" datetime [not null]
  "estado" bit [not null, default: 1]
}

Table "dbo"."Mascota" {
  "idMascota" int [pk, not null, ref: > "dbo"."Dueno_Mascota"."id_Mascota"]
  "nombre" varchar(255)
  "id_Especie" int [ref: > "dbo"."EspecieRaza"."id"]
  "id_Raza" int [ref: > "dbo"."EspecieRaza"."id_Especie"]
}

Table "dbo"."Asociado" {
  "idAsociado" int [pk, not null]
  "nombre" nvarchar(255) [not null]
  "ruc" varchar(255) [not null]
  "nombreDueno" varchar(255) [not null]
  "apellidoDueno" varchar(255) [not null]
  "id_NivelSuscripcion" int [not null, ref: > "dbo"."NivelSuscripcion"."idNivel"]
  "activo" bit [not null]
  "fechaCreacion" datetime [not null]
}

Table "dbo"."EmpleadoAsociado" {
  "idEmpleadoAsociado" int [pk, not null]
  "id_Asociado" int [not null, ref: > "dbo"."Asociado"."idAsociado"]
  "usuario" nvarchar(255) [not null]
  "contrasena" nvarchar(255) [not null]
  "nombreEmpleado" varchar(255) [not null]
  "apellidoPaterno" varchar(255) [not null]
  "ApellidoMaterno" varchar(255) [not null]
  "nroDocumento" varchar(255) [not null]
  "fechaNacimiento" datetime [not null]
  "id_DocumentoIdentidad" int [not null, ref: > "dbo"." DocumentoIdentidd"."idDocumentoIdentidad"]
  "id_Asociado_2" int [not null]
  "id_RolesClinica" int [not null]
}

Table "dbo"."CategoriaServicio" {
  "idCategoriaServicio" int [pk, not null]
  "nombre" varchar(255) [not null]
  "id_Categoria" int
  "id_Asociado" int [not null, ref: > "dbo"."Asociado"."idAsociado"]
}

Table "dbo"."Dueno_Mascota" {
  "idDuenoMascota" int [pk, not null]
  "id_Dueno" int [ref: > "dbo"."Dueno"."idDueno"]
  "id_Mascota" int
  "id_Asociado" int [not null, ref: > "dbo"."Asociado"."idAsociado"]
}

Table "dbo"."Permiso" {
  "idPermiso" int [pk, not null, ref: > "dbo"."Rol_Permiso"."id_Permiso"]
  "nombrePermiso" varchar(255) [not null]
  "descripcionPermiso" nvarchar(255) [not null]
  "id_Asociado" int [not null, ref: > "dbo"."Asociado"."idAsociado"]
}

Table "dbo"."Rol_Permiso" {
  "id_Rol_Permiso" int [pk, not null]
  "id_RolesClinica" int [not null, ref: > "dbo"."RolesClinica"."idRoles"]
  "id_Permiso" int [not null]
  "id_Asociado" int [not null, ref: > "dbo"."Asociado"."idAsociado"]
}

Table "dbo"."RolesClinica" {
  "idRoles" int [pk, not null]
  "nombreRol" varchar(255) [not null]
  "fechaCreacion" datetime [not null]
  "estado" bit [not null]
  "id_Asociado" int [not null, ref: > "dbo"."Asociado"."idAsociado"]
}

Table "dbo"."NivelSuscripcion" {
  "idNivel" int [pk, not null]
  "nombre" nvarchar(255) [not null]
  "cantidadUsuario" int [not null]
  "precioMensual" decimal [not null]
  "precioAnual" decimal [not null]
  "estado" bit [not null]
  "fechaCreacion" datetime [not null]
}

Table "dbo"."Turno" {
  "idTurno" int [pk, not null]
  "nombre" bigint [not null]
  "horaInicio" time [not null]
  "horaFin" time [not null]
  "fechaCreacion" datetime [not null]
  "fechaModificacion" datetime
  "fechaEliminacion" datetime
  "estado" bit [not null]
  "id_Asocido" int [not null]
}

Table "dbo"."EspecieRaza" {
  "id" int [pk, not null]
  "nombre" varchar(500) [not null]
  "id_Especie" int
  "estado" bit [not null]
  "fechaCreacion" datetime
  "fechaModificacion" datetime [not null]
  "fechaEliminacion" datetime [not null]
  "id_Asociado" bigint
}

Table "dbo"."Programacion" {
  "idProgramacion" int [pk, not null]
  "fecha" date [not null]
  "id_EmpleadoAsociado" int [not null, ref: > "dbo"."EmpleadoAsociado"."idEmpleadoAsociado"]
  "id_Turno" int [not null, ref: > "dbo"."Turno"."idTurno"]
  "id_EmpleadoRegistrador" int [not null, ref: > "dbo"."EmpleadoAsociado"."idEmpleadoAsociado"]
  "id_EstadoProgramacion" int [not null, ref: > "dbo"."EstadoProgramacion"."idEstadoProgramacion"]
  "fechaCreacion" datetime [not null]
  "fechaModificacion" datetime
  "fechaEliminacion" datetime
  "id_asociado" int [not null]
  "id_Categoria" int [not null, ref: > "dbo"."CategoriaServicio"."idCategoriaServicio"]
  "id_Servicio" int [not null, ref: > "dbo"."CategoriaServicio"."idCategoriaServicio"]
}

Table "dbo"."CitaProgramada" {
  "idCitaProgramada" int [pk, not null, ref: - "dbo"."Triaje"."id_CitaProgramada", ref: - "dbo"."Atencion"."id_CitaProgramada"]
  "id_Dueño" int [not null, ref: > "dbo"."Dueno"."idDueno"]
  "id_Programacion" int [not null, ref: > "dbo"."Programacion"."idProgramacion"]
  "id_Mascota" int [not null, ref: > "dbo"."Mascota"."idMascota"]
  "fecha" date [not null]
  "horaFin" time
  "id_EstadoCita" int [not null, ref: > "dbo"."EstadoCita"."idEstadoCita"]
  "motivo" varchar(500) [not null]
  "id_Asociado" int
  "horaInicio" time [not null]
  "id_Categoria" int [not null, ref: > "dbo"."CategoriaServicio"."idCategoriaServicio"]
  "id_Servicio" int [not null, ref: > "dbo"."CategoriaServicio"."idCategoriaServicio"]
}

Table "dbo"."EstadoProgramacion" {
  "idEstadoProgramacion" int [pk, not null]
  "nombre" varchar(500) [not null]
  "descripcion" varchar(500) [not null]
  "id_Asociado" int [not null]
  "estado" bit
}

Table "dbo"."EstadoCita" {
  "idEstadoCita" int [pk, not null]
  "nombre" varchar(500) [not null]
  "descripcion" nvarchar(500)
}

Table "dbo"."Receta" {
  "idReceta" int [pk, not null]
  "id_Consulta" int [not null, ref: - "dbo"."AtencionConsulta"."idConsulta"]
  "fechaReceta" datetime [not null]
  "id_EmpladoAsociado" int [not null]
  "id_Asociado" int [not null]
  "fechaCreacion" datetime [not null]
  "fechaModificacion" datetime
  "fechaEliminacion" datetime
}

Table "dbo"."RecetaDetalle" {
  "idRecetDetalle" int [pk, not null]
  "id_Receta" int [not null, ref: > "dbo"."Receta"."idReceta"]
  "id_Medicamentos" int [not null]
  "dosis" varchar(500) [not null]
  "frecuencia" varchar(500) [not null]
  "duracion" varchar(500) [not null]
  "viaAdministracion" int [not null]
  "indicacionesEspecificas" nvarchar(500)
}

Table "dbo"."VacunaAplicada" {
  "id" bigint [pk, not null]
}

Table "dbo"."Examen" {
  "id" bigint [pk, not null]
}

Table "dbo"."EstadoSalidaAtencion" {
  "idEstadoSalida" int [pk, not null, ref: - "dbo"."Atencion"."id_EstadoSalida"]
  "nombre" varchar(500)
  "descripcion" nvarchar(500)
}

Table "dbo"."Triaje" {
  "idTriaje" int [pk, not null, ref: - "dbo"."TriajeDetalle"."id_Triaje", ref: - "dbo"."Atencion"."id_Triaje"]
  "id_CitaProgramada" int
  "codigoTemporal" varchar(500)
  "id_Mascota" int
  "prioridad" int
  "fechaCreacion" datetime [not null]
  "fechaModificacion" datetime
  "fechaEliminacion" datetime
  "id_Asociado" int [not null]
  "id_EmpleadoAsociado" int [not null]
  "id_MetodoIngreso" int [ref: > "dbo"."MetodoIngreso"."idMetodoIngreso"]
}

Table "dbo"."TriajeDetalle" {
  "idTriajeDetlle" int [pk, not null]
  "temperatura" decimal
  "peso" decimal
  "Observaciones" varchar(500)
  "alergias" nvarchar(500)
  "id_Triaje" int
}

Table "dbo"."MetodoIngreso" {
  "idMetodoIngreso" int [pk, not null]
  "nombre" varchar(500)
  "descripcion" varchar(500)
  "id_Asociado" int
  "estado" bit
}

Table "dbo"."AtencionConsulta" {
  "idConsulta" int [pk, not null, ref: - "dbo"."Anamnesis"."Id_Consulta", ref: - "dbo"."Consulta_Diagnostico"."id_Consulta"]
  "id_Atencion" int [not null]
  "evaluacionClinica" nvarchar(500) [not null]
  "pronostico" nvarchar(500)
  "tratamiento" nvarchar(500) [not null]
  "indicaciones" nvarchar(500) [not null]
  "Observaciones" nvarchar(500) [not null]
  "requiereControl" bit [not null]
  "fechaProximoControl" date [not null]
  "fechCreacion" datetime [not null]
  "fechaModificacion" datetime
  "fechaEliminacion" datetime
  "motivoConsulta" varchar(500) [not null]
  "id_NivelRiesgo" int [not null, ref: > "dbo"."NivelRiesgo"."idNivelRiesgo"]
}

Table "dbo"."AtencionEstetica" {
  "idEstetica" int [pk, not null]
  "id_Atencion" int
}

Table "dbo"."Atencion" {
  "idAtencion" int [pk, not null, ref: - "dbo"."AtencionConsulta"."id_Atencion", ref: - "dbo"."AtencionEstetica"."id_Atencion", ref: - "dbo"."AtencionVacunacion"."id_Atencion"]
  "id_CitaProgramada" int [unique]
  "id_Triaje" int [unique]
  "id_EmpleadoAsociado" int [not null]
  "id_Asociado" int [not null]
  "fechaAtencion" date [not null]
  "horaInicio" time [not null]
  "horaFin" time
  "observacion" varchar(500) [not null]
  "id_EstadoSalida" int [not null]
  "fechaCreacion" datetime [not null]
  "fechaModificacion" datetime
  "fechaEliminacion" datetime
}

Table "dbo"."AtencionVacunacion" {
  "idVacunacion" int [pk, not null]
  "id_Atencion" int [not null]
}

Table "dbo"."Anamnesis" {
  "idAnamnesis" int [pk, not null]
  "Id_Consulta" int [not null]
  "antecedentes" nvarchar(500)
  "alergias" int [not null]
  "cirugiasAnteriores" int [not null]
  "medicamentosActuales" nvarchar(500)
  "alimentacion" nvarchar(500)
  "comportamiento" nvarchar(500)
  "inicioSintomas" nvarchar(500)
  "evolucionSintomas" nvarchar(500)
  "observaciones" nvarchar(500)
  "detalleAlergias" nvarchar(500)
  "detalleCirugias" nvarchar(500)
  "historialVacunacion" nvarchar(500)
  "estiloVida" nvarchar(500)
  "historilReproductivo" int [not null]
  "reproduccionDetalle" nvarchar(500)
}

Table "dbo"."Confirmaciones" {
  "idConfirmacion" int [pk, not null, ref: - "dbo"."Anamnesis"."cirugiasAnteriores", ref: - "dbo"."Anamnesis"."alergias", ref: - "dbo"."Anamnesis"."historilReproductivo"]
  "descripcion" nvarchar(500) [not null]
}

Table "dbo"."NivelRiesgo" {
  "idNivelRiesgo" int [pk, not null]
  "nombre" varchar(500)
  "descripcion" varchar(500)
  "codigo" varchar(500)
}

Table "dbo"."MedicamentoCatalogo" {
  "idMedicamento" int [pk, not null, ref: - "dbo"."RecetaDetalle"."id_Medicamentos"]
  "codigoMedicamento" nvarchar(500) [not null]
  "nombreMedicamento" nvarchar(500) [not null]
  "descripcion" nvarchar(500) [not null]
  "concentracion" nvarchar(500) [not null]
  "presentacion" varchar(500) [not null]
  "estado" bit [not null]
}

Table "dbo"."Consulta_Diagnostico" {
  "idDiagnostico" int [pk, not null]
  "id_Consulta" int [not null]
  "id_DiagnosticoCatalogo" int [not null]
}

Table "dbo"."DiagnosticoCatalogo" {
  "idDiagnosticoCatalogo" int [pk, not null, ref: > "dbo"."Consulta_Diagnostico"."id_DiagnosticoCatalogo"]
  "codigoDiagnostico" nvarchar(500) [not null]
  "nombreDiagnostico" nvarchar(500) [not null]
  "descripcion" nvarchar(500) [not null]
}
